version: "3"

services:
  mysql:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 30s
      retries: 3
    platform: "linux/x86_64"
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: shop
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  # app:
  #   build:
  #     context: .
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   environment:
  #     COOKIE_SECRET: abcdefgh123j12i31ioj312io3j12ij
  #     NODE_ENV: dev
  #     MYSQL_HOST: mysql
  #     MYSQL_PORT: 3306
  #     MYSQL_USER: mysql
  #     MYSQL_PASSWORD: mysql
  #     MYSQL_DB_NAME: shop
  #   ports:
  #     - "1337:4000"
volumes:
  mysql-data:
